### ISSUE TITLE
user api should return user details as response not user details in form of string

### ISSUE THREAD

**Issue by sugandhakhera** [Apoorva2405/food-ordering-backend#1]

**Comment by swaroopchirravuri** [comment]
we are getting the error in the message about return type of update method in userRepository
{
  "timestamp": "2018-11-28T15:06:24.886+0000",
  "status": 500,
  "error": "Internal Server Error",
  "message": "Modifying queries can only use void or int/Integer as return type!; nested exception is java.lang.IllegalArgumentException: Modifying queries can only use void or int/Integer as return type!",
  "path": "/api/user"
}

**Comment by sugandhakhera** [comment]
able to update now. But response contains only user as string

**Comment by sugandhakhera** [comment]
Fixed.

**Comment by sugandhakhera** [comment]
Fixed.
