### ISSUE TITLE
/api/restrautrant -> For displaying category , [] should not bepresent 

### ISSUE THREAD

**Issue by sugandhakhera** [Apoorva2405/food-ordering-backend#16]
Response Format - 

 {
    "id": 1,
    "restaurantName": "Dominoz",
    "photoUrl": "https://b.zmtcdn.com/data/pictures/4/18528394/6c3590212b3700b1b160422fd8478287.jpg?output-format=webp",
    "userRating": 4.2,
    "avgPrice": 250,
    "numberUsersRated": 99,
    "address": {
      "id": 1,
      "flatBuilNo": "501/31 Mahalaxmi SRA CHS",
      "locality": "Prabhadevi",
      "city": "Mumbai",
      "zipcode": "400015",
      "state": {
        "id": 21,
        "stateName": "Maharashtra"
      }
    },
    "categories": "Chinese, Drinks, Indian, Italian, Rice, Snacks, Sweet Dish"
  }

**Comment by Apoorva2405** [comment]
Fixed:
https://github.com/Apoorva2405/food-ordering-backend/pull/26
