### ISSUE TITLE
Get Restaurants by Category Name- “/api/restaurant/category/{categoryName}” -  Within each restaurant, the list of categories should be displayed in a categories string in an alphabetical order and the items shouldn’t be displayed.

### ISSUE THREAD

**Issue by sugandhakhera** [Apoorva2405/food-ordering-backend#20]
{
    "id": 7,
    "restaurantName": "Oozo",
    "photoUrl": "https://b.zmtcdn.com/data/pictures/4/18528394/6c3590212b3700b1b160422fd8478287.jpg?output-format=webp",
    "userRating": 3.2,
    "avgPrice": 2500,
    "numberUsersRated": 298,
    "address": {
      "id": 7,
      "flat_buil_number": "rwrwrw",
      "locality": "kjdhkjd",
      "city": "mumbai",
      "zipcode": "123421",
      "state_id": 31
    },
    "categories": "[Italian, Indian, Snacks, Sweet Dish, Chinese, Continental]"
  }

Categories List should be alphabetic

**Comment by sugandhakhera** [comment]
This is to be implemented in all restaurant api's

**Comment by sugandhakhera** [comment]
This is to be implemented in all restaurant api's

**Comment by Apoorva2405** [comment]
fixed
