### ISSUE TITLE
Update restrautrant not working. 

### ISSUE THREAD

**Issue by sugandhakhera** [Apoorva2405/food-ordering-backend#22]
{
  "timestamp": "2018-12-01T11:04:32.362+0000",
  "status": 500,
  "error": "Internal Server Error",
  "message": "Modifying queries can only use void or int/Integer as return type!; nested exception is java.lang.IllegalArgumentException: Modifying queries can only use void or int/Integer as return type!",
  "path": "/api/restaurant/6"
}

**Comment by Apoorva2405** [comment]
fixed in https://github.com/Apoorva2405/food-ordering-backend/pull/26
