### ISSUE TITLE
 /restaurant    ->  the list of categories should be displayed in a categories string in an alphabetical order of their category name

### ISSUE THREAD

**Issue by sugandhakhera** [Apoorva2405/food-ordering-backend#33]
O/P Right now ->  

 "id": 8,
    "restaurantName": "3 Wise Monkeys",
    "photoUrl": "https://b.zmtcdn.com/data/res_imagery/42597_RESTAURANT_obp1.jpg",
    "userRating": 4.9,
    "avgPrice": 1100,
    "numberUsersRated": 28,
    "address": {
      "id": 8,
      "flatBuilNo": "The Unicontental, 3rd Road",
      "locality": "Khar",
      "city": "Mumbai",
      "zipcode": "400058",
      "state": {
        "id": 21,
        "stateName": "Maharashtra"
      }
    },
    "categories": "Indian, Snacks, Italian, Chinese, Continental"

**Comment by Apoorva2405** [comment]
fixed
